apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: default
  name: io-test-workflow
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 180s
      children:
        - io-test
    - name: io-test0
      templateType: IOChaos
      deadline: 60s
      ioChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            polardbx/cn-type: rw
        mode: one
        action: latency
        delay: 100ms
        percent: 100
        volumePath: /usr/share/sysbench/tests
    - name: io-test
      templateType: Serial
      deadline: 120s
      children:
        - io-test0
