kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: pod-kill
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      polardbx/cn-type: rw
  mode: one
  action: pod-kill
  gracePeriod: 0
