apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  name: network-workflow
  namespace: default
spec:
  entry: entry
  templates:
    - deadline: 100s
      name: etwork-task-in-serial-flow
      networkChaos:
        action: delay
        delay:
          correlation: "0"
          jitter: 0ms
          latency: 20s
        direction: both
        mode: one
        selector:
          labelSelectors:
            polardbx/cn-type: rw
          namespaces:
            - default
        target:
          mode: one
          selector:
            labelSelectors:
              polardbx/cn-type: rw
            namespaces:
              - default
      templateType: NetworkChaos
    - children:
        - etwork-task-in-serial-flow
      deadline: 120s
      name: network-error
      templateType: Serial
    - children:
        - network-error
      deadline: 200s
      name: entry
      templateType: Serial
